name: Build Plugin

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}

    env:
      PLUGIN_NAME: GainBooster

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install WebView2 (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          Register-PackageSource -ProviderName NuGet -Name nugetRepository -Location https://www.nuget.org/api/v2
          Install-Package Microsoft.Web.WebView2 -Scope CurrentUser -RequiredVersion 1.0.1901.177 -Source nugetRepository -Force

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --installargs "ADD_CMAKE_TO_PATH=1" --yes

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake build-essential pkg-config \
            libasound2-dev libx11-dev libxrandr-dev libxext-dev \
            libfreetype6-dev libfontconfig1-dev libgl1-mesa-dev \
            libcurl4-openssl-dev libgtk-3-dev libwebkit2gtk-4.1-dev
            
      - name: Install npm packages
        run: npm install

      - name: Build project
        run: npm run build

      - name: Remove shared static libraries
        shell: bash
        run: |
          RELEASE_DIR="build/${{env.PLUGIN_NAME}}_artefacts/Release"
          find "$RELEASE_DIR" -type f -name "*.a" -print -delete || true
          find "$RELEASE_DIR" -type f -name "*.lib" -print -delete || true
          find "$RELEASE_DIR" -type f -name "*.exp" -print -delete || true

      - name: Flatten plugin folders
        shell: bash
        run: |
          RELEASE_DIR="build/${{env.PLUGIN_NAME}}_artefacts/Release"
          for subdir in "AU" "VST3" "Standalone"; do
            if [ -d "$RELEASE_DIR/$subdir" ]; then
              mv "$RELEASE_DIR/$subdir"/* "$RELEASE_DIR"/ 2>/dev/null || true
            fi
          done
          rmdir "$RELEASE_DIR/AU" 2>/dev/null || true
          rmdir "$RELEASE_DIR/VST3" 2>/dev/null || true
          rmdir "$RELEASE_DIR/Standalone" 2>/dev/null || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.PLUGIN_NAME}}-${{matrix.os}}
          path: build/${{env.PLUGIN_NAME}}_artefacts/Release